/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type BlogPostCta = {
  _type: 'blogPostCta'
  title: string
  description?: string
  buttonText: string
  buttonUrl: string
}

export type HtmlEmbed = {
  _type: 'htmlEmbed'
  html: string
}

export type TextBlock = {
  _type: 'textBlock'
  body: BlockContentSeo
}

export type BlockContentSeo = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    follow?: boolean
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type AuthorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'author'
}

export type BlogPostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'blogPost'
}

export type BlogPost = {
  _id: string
  _type: 'blogPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  metaTitle?: string
  metaDescription: string
  slug: Slug
  keywordPrimary: string
  keywordsSecondary?: string
  category: CategoryReference
  tags?: Array<string>
  featuredImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  featuredImageAlt: string
  schemaPrincipalType?: 'Article' | 'BlogPosting'
  structuredDataJsonLd?: string
  h1: string
  author: AuthorReference
  publishedAt: string
  updatedAt?: string
  introduction: BlockContentSeo
  keyTakeaways?: Array<{
    text: string
    _key: string
  }>
  body?: BlockContentSeo
  content?: Array<
    | ({
        _key: string
      } & TextBlock)
    | ({
        _key: string
      } & HtmlEmbed)
  >
  faq?: Array<{
    question: string
    answer: BlockContentSeo
    _key: string
  }>
  conclusion?: BlockContentSeo
  ctaFinal?: BlogPostCta
  sources?: Array<{
    label: string
    url: string
    _key: string
  }>
  relatedPosts?: Array<
    {
      _key: string
    } & BlogPostReference
  >
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  role?: string
  photo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bio?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | PageReference
  | PostReference
  | Link
  | SanityImageAssetReference
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | BlogPostCta
  | HtmlEmbed
  | TextBlock
  | BlockContentSeo
  | CategoryReference
  | AuthorReference
  | BlogPostReference
  | BlogPost
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | Settings
  | Page
  | PersonReference
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,            link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        button: {
          _type: 'button'
          buttonText?: string
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
          } | null
        } | null
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light'
        contentAlignment?: 'imageFirst' | 'textFirst'
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        > | null
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type in ["page", "post", "blogPost"] && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      _type: 'blogPost'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'post'
      _updatedAt: string
    }
>

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type in ["post", "blogPost"] && defined(slug.current)] | order(coalesce(publishedAt, date, _updatedAt) desc) {      _id,  _type,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(metaTitle, title, h1, "Untitled"),  "slug": slug.current,  "excerpt": coalesce(metaDescription, excerpt, ""),  "coverImage": coalesce(featuredImage, coverImage),  featuredImageAlt,  "date": coalesce(publishedAt, date, _updatedAt),  "author": coalesce(    author->{ "firstName": name, "lastName": "", "picture": photo, role, bio },    author->{ firstName, lastName, picture }  ),  category->{ title, "slug": slug.current },  tags,  keywordPrimary,  keywordsSecondary,  keyTakeaways,  h1,  introduction,  faq,  conclusion,  ctaFinal,  sources,  structuredDataJsonLd,  schemaPrincipalType  }
export type AllPostsQueryResult = Array<
  | {
      _id: string
      _type: 'blogPost'
      status: 'draft' | 'published'
      title: string
      slug: string
      excerpt: string
      coverImage: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      featuredImageAlt: string
      date: string
      author: {
        firstName: string
        lastName: ''
        picture: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        role: string | null
        bio: string | null
      }
      category: {
        title: string
        slug: string
      }
      tags: Array<string> | null
      keywordPrimary: string
      keywordsSecondary: string | null
      keyTakeaways: Array<{
        text: string
        _key: string
      }> | null
      h1: string
      introduction: BlockContentSeo
      faq: Array<{
        question: string
        answer: BlockContentSeo
        _key: string
      }> | null
      conclusion: BlockContentSeo | null
      ctaFinal: BlogPostCta | null
      sources: Array<{
        label: string
        url: string
        _key: string
      }> | null
      structuredDataJsonLd: string | null
      schemaPrincipalType: 'Article' | 'BlogPosting' | null
    }
  | {
      _id: string
      _type: 'post'
      status: 'draft' | 'published'
      title: string
      slug: string
      excerpt: string | ''
      coverImage: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
      } | null
      featuredImageAlt: null
      date: string
      author:
        | {
            firstName: null
            lastName: ''
            picture: null
            role: null
            bio: null
          }
        | {
            firstName: string
            lastName: string
            picture: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | null
      category: null
      tags: null
      keywordPrimary: null
      keywordsSecondary: null
      keyTakeaways: null
      h1: null
      introduction: null
      faq: null
      conclusion: null
      ctaFinal: null
      sources: null
      structuredDataJsonLd: null
      schemaPrincipalType: null
    }
>

// Source: sanity/lib/queries.ts
// Variable: morePostsQuery
// Query: *[_type in ["post", "blogPost"] && _id != $skip && defined(slug.current)] | order(coalesce(publishedAt, date, _updatedAt) desc) [0...$limit] {      _id,  _type,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(metaTitle, title, h1, "Untitled"),  "slug": slug.current,  "excerpt": coalesce(metaDescription, excerpt, ""),  "coverImage": coalesce(featuredImage, coverImage),  featuredImageAlt,  "date": coalesce(publishedAt, date, _updatedAt),  "author": coalesce(    author->{ "firstName": name, "lastName": "", "picture": photo, role, bio },    author->{ firstName, lastName, picture }  ),  category->{ title, "slug": slug.current },  tags,  keywordPrimary,  keywordsSecondary,  keyTakeaways,  h1,  introduction,  faq,  conclusion,  ctaFinal,  sources,  structuredDataJsonLd,  schemaPrincipalType  }
export type MorePostsQueryResult = Array<
  | {
      _id: string
      _type: 'blogPost'
      status: 'draft' | 'published'
      title: string
      slug: string
      excerpt: string
      coverImage: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      featuredImageAlt: string
      date: string
      author: {
        firstName: string
        lastName: ''
        picture: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        role: string | null
        bio: string | null
      }
      category: {
        title: string
        slug: string
      }
      tags: Array<string> | null
      keywordPrimary: string
      keywordsSecondary: string | null
      keyTakeaways: Array<{
        text: string
        _key: string
      }> | null
      h1: string
      introduction: BlockContentSeo
      faq: Array<{
        question: string
        answer: BlockContentSeo
        _key: string
      }> | null
      conclusion: BlockContentSeo | null
      ctaFinal: BlogPostCta | null
      sources: Array<{
        label: string
        url: string
        _key: string
      }> | null
      structuredDataJsonLd: string | null
      schemaPrincipalType: 'Article' | 'BlogPosting' | null
    }
  | {
      _id: string
      _type: 'post'
      status: 'draft' | 'published'
      title: string
      slug: string
      excerpt: string | ''
      coverImage: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
      } | null
      featuredImageAlt: null
      date: string
      author:
        | {
            firstName: null
            lastName: ''
            picture: null
            role: null
            bio: null
          }
        | {
            firstName: string
            lastName: string
            picture: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | null
      category: null
      tags: null
      keywordPrimary: null
      keywordsSecondary: null
      keyTakeaways: null
      h1: null
      introduction: null
      faq: null
      conclusion: null
      ctaFinal: null
      sources: null
      structuredDataJsonLd: null
      schemaPrincipalType: null
    }
>

// Source: sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type in ["post", "blogPost"] && slug.current == $slug] [0] {    body[]{        ...,  markDefs[]{    ...,      _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }  }    },    content[]{        ...,  markDefs[]{    ...,      _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }  },      _type == "textBlock" => {        ...,        body[]{            ...,  markDefs[]{    ...,      _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }  }        }      }    },      _id,  _type,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(metaTitle, title, h1, "Untitled"),  "slug": slug.current,  "excerpt": coalesce(metaDescription, excerpt, ""),  "coverImage": coalesce(featuredImage, coverImage),  featuredImageAlt,  "date": coalesce(publishedAt, date, _updatedAt),  "author": coalesce(    author->{ "firstName": name, "lastName": "", "picture": photo, role, bio },    author->{ firstName, lastName, picture }  ),  category->{ title, "slug": slug.current },  tags,  keywordPrimary,  keywordsSecondary,  keyTakeaways,  h1,  introduction,  faq,  conclusion,  ctaFinal,  sources,  structuredDataJsonLd,  schemaPrincipalType  }
export type PostQueryResult =
  | {
      body: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          href?: string
          follow?: boolean
          _type: 'link'
          _key: string
          page: null
          post: null
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }> | null
      content: Array<
        | {
            _key: string
            _type: 'htmlEmbed'
            html: string
            markDefs: null
          }
        | {
            _key: string
            _type: 'textBlock'
            body: Array<{
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h2' | 'h3' | 'h4' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                href?: string
                follow?: boolean
                _type: 'link'
                _key: string
                page: null
                post: null
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }>
            markDefs: null
          }
      > | null
      _id: string
      _type: 'blogPost'
      status: 'draft' | 'published'
      title: string
      slug: string
      excerpt: string
      coverImage: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      featuredImageAlt: string
      date: string
      author: {
        firstName: string
        lastName: ''
        picture: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        role: string | null
        bio: string | null
      }
      category: {
        title: string
        slug: string
      }
      tags: Array<string> | null
      keywordPrimary: string
      keywordsSecondary: string | null
      keyTakeaways: Array<{
        text: string
        _key: string
      }> | null
      h1: string
      introduction: BlockContentSeo
      faq: Array<{
        question: string
        answer: BlockContentSeo
        _key: string
      }> | null
      conclusion: BlockContentSeo | null
      ctaFinal: BlogPostCta | null
      sources: Array<{
        label: string
        url: string
        _key: string
      }> | null
      structuredDataJsonLd: string | null
      schemaPrincipalType: 'Article' | 'BlogPosting' | null
    }
  | {
      body: null
      content: Array<
        | {
            children?: Array<{
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }>
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
            listItem?: 'bullet' | 'number'
            markDefs: Array<{
              linkType?: 'href' | 'page' | 'post'
              href?: string
              page: string | null
              post: string | null
              openInNewTab?: boolean
              _type: 'link'
              _key: string
            }> | null
            level?: number
            _type: 'block'
            _key: string
          }
        | {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
            _key: string
            markDefs: null
          }
      > | null
      _id: string
      _type: 'post'
      status: 'draft' | 'published'
      title: string
      slug: string
      excerpt: string | ''
      coverImage: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
      } | null
      featuredImageAlt: null
      date: string
      author:
        | {
            firstName: null
            lastName: ''
            picture: null
            role: null
            bio: null
          }
        | {
            firstName: string
            lastName: string
            picture: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | null
      category: null
      tags: null
      keywordPrimary: null
      keywordsSecondary: null
      keyTakeaways: null
      h1: null
      introduction: null
      faq: null
      conclusion: null
      ctaFinal: null
      sources: null
      structuredDataJsonLd: null
      schemaPrincipalType: null
    }
  | null

// Source: sanity/lib/queries.ts
// Variable: postPagesSlugs
// Query: *[_type in ["post", "blogPost"] && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type in ["page", "post", "blogPost"] && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type in ["post", "blogPost"] && defined(slug.current)] | order(coalesce(publishedAt, date, _updatedAt) desc) {\n    \n  _id,\n  _type,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(metaTitle, title, h1, "Untitled"),\n  "slug": slug.current,\n  "excerpt": coalesce(metaDescription, excerpt, ""),\n  "coverImage": coalesce(featuredImage, coverImage),\n  featuredImageAlt,\n  "date": coalesce(publishedAt, date, _updatedAt),\n  "author": coalesce(\n    author->{ "firstName": name, "lastName": "", "picture": photo, role, bio },\n    author->{ firstName, lastName, picture }\n  ),\n  category->{ title, "slug": slug.current },\n  tags,\n  keywordPrimary,\n  keywordsSecondary,\n  keyTakeaways,\n  h1,\n  introduction,\n  faq,\n  conclusion,\n  ctaFinal,\n  sources,\n  structuredDataJsonLd,\n  schemaPrincipalType\n\n  }\n': AllPostsQueryResult
    '\n  *[_type in ["post", "blogPost"] && _id != $skip && defined(slug.current)] | order(coalesce(publishedAt, date, _updatedAt) desc) [0...$limit] {\n    \n  _id,\n  _type,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(metaTitle, title, h1, "Untitled"),\n  "slug": slug.current,\n  "excerpt": coalesce(metaDescription, excerpt, ""),\n  "coverImage": coalesce(featuredImage, coverImage),\n  featuredImageAlt,\n  "date": coalesce(publishedAt, date, _updatedAt),\n  "author": coalesce(\n    author->{ "firstName": name, "lastName": "", "picture": photo, role, bio },\n    author->{ firstName, lastName, picture }\n  ),\n  category->{ title, "slug": slug.current },\n  tags,\n  keywordPrimary,\n  keywordsSecondary,\n  keyTakeaways,\n  h1,\n  introduction,\n  faq,\n  conclusion,\n  ctaFinal,\n  sources,\n  structuredDataJsonLd,\n  schemaPrincipalType\n\n  }\n': MorePostsQueryResult
    '\n  *[_type in ["post", "blogPost"] && slug.current == $slug] [0] {\n    body[]{\n      \n  ...,\n  markDefs[]{\n    ...,\n    \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n  }\n\n    },\n    content[]{\n      \n  ...,\n  markDefs[]{\n    ...,\n    \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n  }\n,\n      _type == "textBlock" => {\n        ...,\n        body[]{\n          \n  ...,\n  markDefs[]{\n    ...,\n    \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n  }\n\n        }\n      }\n    },\n    \n  _id,\n  _type,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(metaTitle, title, h1, "Untitled"),\n  "slug": slug.current,\n  "excerpt": coalesce(metaDescription, excerpt, ""),\n  "coverImage": coalesce(featuredImage, coverImage),\n  featuredImageAlt,\n  "date": coalesce(publishedAt, date, _updatedAt),\n  "author": coalesce(\n    author->{ "firstName": name, "lastName": "", "picture": photo, role, bio },\n    author->{ firstName, lastName, picture }\n  ),\n  category->{ title, "slug": slug.current },\n  tags,\n  keywordPrimary,\n  keywordsSecondary,\n  keyTakeaways,\n  h1,\n  introduction,\n  faq,\n  conclusion,\n  ctaFinal,\n  sources,\n  structuredDataJsonLd,\n  schemaPrincipalType\n\n  }\n': PostQueryResult
    '\n  *[_type in ["post", "blogPost"] && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
  }
}
