name: Prettier

on:
  push:
    branches: [main, feat/ci-renovate-prettier, chore-prettier-ignore-generated-files]
    paths-ignore:
      - 'package-lock.json'
      - '**/package-lock.json'
      - 'yarn.lock'
      - '**/yarn.lock'
      - 'pnpm-lock.yaml'
      - '**/pnpm-lock.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*

      - run: npm ci
      - run: npx prettier --check .